// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.2
// source: GWC_PBMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfoClient_ChannelId int32

const (
	DeviceInfoClient_Channel_None DeviceInfoClient_ChannelId = 1
	DeviceInfoClient_Channel_JJ   DeviceInfoClient_ChannelId = 2
)

// Enum value maps for DeviceInfoClient_ChannelId.
var (
	DeviceInfoClient_ChannelId_name = map[int32]string{
		1: "Channel_None",
		2: "Channel_JJ",
	}
	DeviceInfoClient_ChannelId_value = map[string]int32{
		"Channel_None": 1,
		"Channel_JJ":   2,
	}
)

func (x DeviceInfoClient_ChannelId) Enum() *DeviceInfoClient_ChannelId {
	p := new(DeviceInfoClient_ChannelId)
	*p = x
	return p
}

func (x DeviceInfoClient_ChannelId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceInfoClient_ChannelId) Descriptor() protoreflect.EnumDescriptor {
	return file_GWC_PBMessage_proto_enumTypes[0].Descriptor()
}

func (DeviceInfoClient_ChannelId) Type() protoreflect.EnumType {
	return &file_GWC_PBMessage_proto_enumTypes[0]
}

func (x DeviceInfoClient_ChannelId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceInfoClient_ChannelId) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceInfoClient_ChannelId(num)
	return nil
}

// Deprecated: Use DeviceInfoClient_ChannelId.Descriptor instead.
func (DeviceInfoClient_ChannelId) EnumDescriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{11, 0}
}

type CGW_CLIENT_LOGIN_LoginType int32

const (
	CGW_CLIENT_LOGIN_TEST_LOGIN CGW_CLIENT_LOGIN_LoginType = 1
	CGW_CLIENT_LOGIN_JJ_LOGIN   CGW_CLIENT_LOGIN_LoginType = 2
	CGW_CLIENT_LOGIN_GM_LOGIN   CGW_CLIENT_LOGIN_LoginType = 3
)

// Enum value maps for CGW_CLIENT_LOGIN_LoginType.
var (
	CGW_CLIENT_LOGIN_LoginType_name = map[int32]string{
		1: "TEST_LOGIN",
		2: "JJ_LOGIN",
		3: "GM_LOGIN",
	}
	CGW_CLIENT_LOGIN_LoginType_value = map[string]int32{
		"TEST_LOGIN": 1,
		"JJ_LOGIN":   2,
		"GM_LOGIN":   3,
	}
)

func (x CGW_CLIENT_LOGIN_LoginType) Enum() *CGW_CLIENT_LOGIN_LoginType {
	p := new(CGW_CLIENT_LOGIN_LoginType)
	*p = x
	return p
}

func (x CGW_CLIENT_LOGIN_LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CGW_CLIENT_LOGIN_LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_GWC_PBMessage_proto_enumTypes[1].Descriptor()
}

func (CGW_CLIENT_LOGIN_LoginType) Type() protoreflect.EnumType {
	return &file_GWC_PBMessage_proto_enumTypes[1]
}

func (x CGW_CLIENT_LOGIN_LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CGW_CLIENT_LOGIN_LoginType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CGW_CLIENT_LOGIN_LoginType(num)
	return nil
}

// Deprecated: Use CGW_CLIENT_LOGIN_LoginType.Descriptor instead.
func (CGW_CLIENT_LOGIN_LoginType) EnumDescriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{12, 0}
}

// #Client Connect to GateServer
// @CGW
type CGW_VERIFY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 登录基本数据
	Userinfo    *string `protobuf:"bytes,1,opt,name=userinfo" json:"userinfo,omitempty"`        //玩家的信息
	Isreconnect *int32  `protobuf:"varint,2,opt,name=isreconnect" json:"isreconnect,omitempty"` //是否是断线重连
	Centerid    *int32  `protobuf:"varint,3,opt,name=centerid" json:"centerid,omitempty"`       //连接的center服务器id
}

func (x *CGW_VERIFY) Reset() {
	*x = CGW_VERIFY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_VERIFY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_VERIFY) ProtoMessage() {}

func (x *CGW_VERIFY) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_VERIFY.ProtoReflect.Descriptor instead.
func (*CGW_VERIFY) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{0}
}

func (x *CGW_VERIFY) GetUserinfo() string {
	if x != nil && x.Userinfo != nil {
		return *x.Userinfo
	}
	return ""
}

func (x *CGW_VERIFY) GetIsreconnect() int32 {
	if x != nil && x.Isreconnect != nil {
		return *x.Isreconnect
	}
	return 0
}

func (x *CGW_VERIFY) GetCenterid() int32 {
	if x != nil && x.Centerid != nil {
		return *x.Centerid
	}
	return 0
}

// #Client Connect to GateServer
// @GWC
type GWC_VERIFY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 登录基本数据
	Result      *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`           //
	Isreconnect *int32 `protobuf:"varint,2,opt,name=isreconnect" json:"isreconnect,omitempty"` //是否是断线重连
}

func (x *GWC_VERIFY) Reset() {
	*x = GWC_VERIFY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWC_VERIFY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWC_VERIFY) ProtoMessage() {}

func (x *GWC_VERIFY) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWC_VERIFY.ProtoReflect.Descriptor instead.
func (*GWC_VERIFY) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{1}
}

func (x *GWC_VERIFY) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *GWC_VERIFY) GetIsreconnect() int32 {
	if x != nil && x.Isreconnect != nil {
		return *x.Isreconnect
	}
	return 0
}

// #Client Connect to GateServer
// @CGW
type CGW_HEART struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userinfo *string `protobuf:"bytes,1,opt,name=userinfo" json:"userinfo,omitempty"` //玩家的信息
}

func (x *CGW_HEART) Reset() {
	*x = CGW_HEART{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_HEART) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_HEART) ProtoMessage() {}

func (x *CGW_HEART) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_HEART.ProtoReflect.Descriptor instead.
func (*CGW_HEART) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{2}
}

func (x *CGW_HEART) GetUserinfo() string {
	if x != nil && x.Userinfo != nil {
		return *x.Userinfo
	}
	return ""
}

// #Client Connect to GateServer
// @CGW
type CGW_CONNECT_GAMESERVER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameserverid *int32 `protobuf:"varint,1,opt,name=gameserverid" json:"gameserverid,omitempty"` //game server 的id
	Isreconnect  *int32 `protobuf:"varint,2,opt,name=isreconnect" json:"isreconnect,omitempty"`   //是否是断线重连
}

func (x *CGW_CONNECT_GAMESERVER) Reset() {
	*x = CGW_CONNECT_GAMESERVER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_CONNECT_GAMESERVER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_CONNECT_GAMESERVER) ProtoMessage() {}

func (x *CGW_CONNECT_GAMESERVER) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_CONNECT_GAMESERVER.ProtoReflect.Descriptor instead.
func (*CGW_CONNECT_GAMESERVER) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{3}
}

func (x *CGW_CONNECT_GAMESERVER) GetGameserverid() int32 {
	if x != nil && x.Gameserverid != nil {
		return *x.Gameserverid
	}
	return 0
}

func (x *CGW_CONNECT_GAMESERVER) GetIsreconnect() int32 {
	if x != nil && x.Isreconnect != nil {
		return *x.Isreconnect
	}
	return 0
}

// #Client Connect to GateServer
// @GWC
type GWC_CONNECT_GAMESERVER_RET struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suc         *int32 `protobuf:"varint,1,opt,name=suc" json:"suc,omitempty"`                 //game server 的id
	Isreconnect *int32 `protobuf:"varint,2,opt,name=isreconnect" json:"isreconnect,omitempty"` //是否是断线重连
}

func (x *GWC_CONNECT_GAMESERVER_RET) Reset() {
	*x = GWC_CONNECT_GAMESERVER_RET{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWC_CONNECT_GAMESERVER_RET) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWC_CONNECT_GAMESERVER_RET) ProtoMessage() {}

func (x *GWC_CONNECT_GAMESERVER_RET) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWC_CONNECT_GAMESERVER_RET.ProtoReflect.Descriptor instead.
func (*GWC_CONNECT_GAMESERVER_RET) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{4}
}

func (x *GWC_CONNECT_GAMESERVER_RET) GetSuc() int32 {
	if x != nil && x.Suc != nil {
		return *x.Suc
	}
	return 0
}

func (x *GWC_CONNECT_GAMESERVER_RET) GetIsreconnect() int32 {
	if x != nil && x.Isreconnect != nil {
		return *x.Isreconnect
	}
	return 0
}

// #Client Connect to GateServer
// @CGW
type CGW_REQUEST_GAMESERVERINFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Useraccount *string `protobuf:"bytes,1,opt,name=useraccount" json:"useraccount,omitempty"` //玩家的信息
}

func (x *CGW_REQUEST_GAMESERVERINFO) Reset() {
	*x = CGW_REQUEST_GAMESERVERINFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_REQUEST_GAMESERVERINFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_REQUEST_GAMESERVERINFO) ProtoMessage() {}

func (x *CGW_REQUEST_GAMESERVERINFO) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_REQUEST_GAMESERVERINFO.ProtoReflect.Descriptor instead.
func (*CGW_REQUEST_GAMESERVERINFO) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{5}
}

func (x *CGW_REQUEST_GAMESERVERINFO) GetUseraccount() string {
	if x != nil && x.Useraccount != nil {
		return *x.Useraccount
	}
	return ""
}

// #Client Connect to GateServer
// @GWC
type GWC_REQUEST_GAMESERVERINFO_RET struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameserverid *int32 `protobuf:"varint,1,opt,name=gameserverid" json:"gameserverid,omitempty"`
}

func (x *GWC_REQUEST_GAMESERVERINFO_RET) Reset() {
	*x = GWC_REQUEST_GAMESERVERINFO_RET{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWC_REQUEST_GAMESERVERINFO_RET) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWC_REQUEST_GAMESERVERINFO_RET) ProtoMessage() {}

func (x *GWC_REQUEST_GAMESERVERINFO_RET) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWC_REQUEST_GAMESERVERINFO_RET.ProtoReflect.Descriptor instead.
func (*GWC_REQUEST_GAMESERVERINFO_RET) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{6}
}

func (x *GWC_REQUEST_GAMESERVERINFO_RET) GetGameserverid() int32 {
	if x != nil && x.Gameserverid != nil {
		return *x.Gameserverid
	}
	return 0
}

// #client reconnect
// @CGW
type CGW_RECONNECT_GAMESERVER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 断线重连
	Account *string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Objid   *int32  `protobuf:"varint,2,opt,name=objid" json:"objid,omitempty"`
}

func (x *CGW_RECONNECT_GAMESERVER) Reset() {
	*x = CGW_RECONNECT_GAMESERVER{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_RECONNECT_GAMESERVER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_RECONNECT_GAMESERVER) ProtoMessage() {}

func (x *CGW_RECONNECT_GAMESERVER) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_RECONNECT_GAMESERVER.ProtoReflect.Descriptor instead.
func (*CGW_RECONNECT_GAMESERVER) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{7}
}

func (x *CGW_RECONNECT_GAMESERVER) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *CGW_RECONNECT_GAMESERVER) GetObjid() int32 {
	if x != nil && x.Objid != nil {
		return *x.Objid
	}
	return 0
}

// #Client Connect to GateServer
// @GWC
type GWC_HEART struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servertime *string `protobuf:"bytes,1,opt,name=servertime" json:"servertime,omitempty"`
}

func (x *GWC_HEART) Reset() {
	*x = GWC_HEART{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWC_HEART) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWC_HEART) ProtoMessage() {}

func (x *GWC_HEART) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWC_HEART.ProtoReflect.Descriptor instead.
func (*GWC_HEART) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{8}
}

func (x *GWC_HEART) GetServertime() string {
	if x != nil && x.Servertime != nil {
		return *x.Servertime
	}
	return ""
}

// #Client Connect to GateServer
// @CGW
type CGW_CLIENT_HEART struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CGW_CLIENT_HEART) Reset() {
	*x = CGW_CLIENT_HEART{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_CLIENT_HEART) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_CLIENT_HEART) ProtoMessage() {}

func (x *CGW_CLIENT_HEART) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_CLIENT_HEART.ProtoReflect.Descriptor instead.
func (*CGW_CLIENT_HEART) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{9}
}

// #Client Connect to GateServer
// @GWC
type GWC_CLIENT_HEART struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GWC_CLIENT_HEART) Reset() {
	*x = GWC_CLIENT_HEART{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWC_CLIENT_HEART) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWC_CLIENT_HEART) ProtoMessage() {}

func (x *GWC_CLIENT_HEART) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWC_CLIENT_HEART.ProtoReflect.Descriptor instead.
func (*GWC_CLIENT_HEART) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{10}
}

type DeviceInfoClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceModel  *string `protobuf:"bytes,1,opt,name=deviceModel" json:"deviceModel,omitempty"`
	DeviceHeight *string `protobuf:"bytes,2,opt,name=deviceHeight" json:"deviceHeight,omitempty"`
	DeviceWidth  *string `protobuf:"bytes,3,opt,name=deviceWidth" json:"deviceWidth,omitempty"`
	OsName       *string `protobuf:"bytes,4,opt,name=osName" json:"osName,omitempty"`
	OsVersion    *string `protobuf:"bytes,5,opt,name=osVersion" json:"osVersion,omitempty"`
	MacAddress   *string `protobuf:"bytes,6,opt,name=macAddress" json:"macAddress,omitempty"`
	Udid         *string `protobuf:"bytes,7,opt,name=udid" json:"udid,omitempty"`
	Nation       *string `protobuf:"bytes,8,opt,name=nation" json:"nation,omitempty"`
	Isp          *string `protobuf:"bytes,9,opt,name=isp" json:"isp,omitempty"`
	Network      *string `protobuf:"bytes,10,opt,name=network" json:"network,omitempty"`
	AppChannel   *string `protobuf:"bytes,11,opt,name=appChannel" json:"appChannel,omitempty"`
	AppVersion   *string `protobuf:"bytes,12,opt,name=appVersion" json:"appVersion,omitempty"`
	Imei         *string `protobuf:"bytes,13,opt,name=imei" json:"imei,omitempty"`
	HardwareInfo *string `protobuf:"bytes,14,opt,name=HardwareInfo" json:"HardwareInfo,omitempty"`
}

func (x *DeviceInfoClient) Reset() {
	*x = DeviceInfoClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfoClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoClient) ProtoMessage() {}

func (x *DeviceInfoClient) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoClient.ProtoReflect.Descriptor instead.
func (*DeviceInfoClient) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceInfoClient) GetDeviceModel() string {
	if x != nil && x.DeviceModel != nil {
		return *x.DeviceModel
	}
	return ""
}

func (x *DeviceInfoClient) GetDeviceHeight() string {
	if x != nil && x.DeviceHeight != nil {
		return *x.DeviceHeight
	}
	return ""
}

func (x *DeviceInfoClient) GetDeviceWidth() string {
	if x != nil && x.DeviceWidth != nil {
		return *x.DeviceWidth
	}
	return ""
}

func (x *DeviceInfoClient) GetOsName() string {
	if x != nil && x.OsName != nil {
		return *x.OsName
	}
	return ""
}

func (x *DeviceInfoClient) GetOsVersion() string {
	if x != nil && x.OsVersion != nil {
		return *x.OsVersion
	}
	return ""
}

func (x *DeviceInfoClient) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

func (x *DeviceInfoClient) GetUdid() string {
	if x != nil && x.Udid != nil {
		return *x.Udid
	}
	return ""
}

func (x *DeviceInfoClient) GetNation() string {
	if x != nil && x.Nation != nil {
		return *x.Nation
	}
	return ""
}

func (x *DeviceInfoClient) GetIsp() string {
	if x != nil && x.Isp != nil {
		return *x.Isp
	}
	return ""
}

func (x *DeviceInfoClient) GetNetwork() string {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return ""
}

func (x *DeviceInfoClient) GetAppChannel() string {
	if x != nil && x.AppChannel != nil {
		return *x.AppChannel
	}
	return ""
}

func (x *DeviceInfoClient) GetAppVersion() string {
	if x != nil && x.AppVersion != nil {
		return *x.AppVersion
	}
	return ""
}

func (x *DeviceInfoClient) GetImei() string {
	if x != nil && x.Imei != nil {
		return *x.Imei
	}
	return ""
}

func (x *DeviceInfoClient) GetHardwareInfo() string {
	if x != nil && x.HardwareInfo != nil {
		return *x.HardwareInfo
	}
	return ""
}

// #Client Send Login to GateServer
// @CGW
type CGW_CLIENT_LOGIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameVersion *string           `protobuf:"bytes,1,req,name=GameVersion" json:"GameVersion,omitempty"`
	MaxPacketId *int32            `protobuf:"varint,2,req,name=MaxPacketId" json:"MaxPacketId,omitempty"`
	DeviceInfo  *DeviceInfoClient `protobuf:"bytes,3,req,name=deviceInfo" json:"deviceInfo,omitempty"`
	Account     *string           `protobuf:"bytes,4,opt,name=Account" json:"Account,omitempty"`
	Type        *int32            `protobuf:"varint,5,req,name=type" json:"type,omitempty"`
	Token       *string           `protobuf:"bytes,6,opt,name=token" json:"token,omitempty"`
	Uuid        *string           `protobuf:"bytes,7,opt,name=uuid" json:"uuid,omitempty"`
}

func (x *CGW_CLIENT_LOGIN) Reset() {
	*x = CGW_CLIENT_LOGIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_CLIENT_LOGIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_CLIENT_LOGIN) ProtoMessage() {}

func (x *CGW_CLIENT_LOGIN) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_CLIENT_LOGIN.ProtoReflect.Descriptor instead.
func (*CGW_CLIENT_LOGIN) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{12}
}

func (x *CGW_CLIENT_LOGIN) GetGameVersion() string {
	if x != nil && x.GameVersion != nil {
		return *x.GameVersion
	}
	return ""
}

func (x *CGW_CLIENT_LOGIN) GetMaxPacketId() int32 {
	if x != nil && x.MaxPacketId != nil {
		return *x.MaxPacketId
	}
	return 0
}

func (x *CGW_CLIENT_LOGIN) GetDeviceInfo() *DeviceInfoClient {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *CGW_CLIENT_LOGIN) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *CGW_CLIENT_LOGIN) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *CGW_CLIENT_LOGIN) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *CGW_CLIENT_LOGIN) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

// #Client Query Gate Info
// @CGW
type CGW_QUERY_GATE_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CGW_QUERY_GATE_INFO) Reset() {
	*x = CGW_QUERY_GATE_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CGW_QUERY_GATE_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGW_QUERY_GATE_INFO) ProtoMessage() {}

func (x *CGW_QUERY_GATE_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGW_QUERY_GATE_INFO.ProtoReflect.Descriptor instead.
func (*CGW_QUERY_GATE_INFO) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{13}
}

// #Gate Return Info To Client
// @GWC
type GWC_QUERY_GATE_INFO_RET struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"` //gate ip
	Port    *uint32 `protobuf:"varint,2,req,name=port" json:"port,omitempty"`      //gate port
}

func (x *GWC_QUERY_GATE_INFO_RET) Reset() {
	*x = GWC_QUERY_GATE_INFO_RET{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GWC_PBMessage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWC_QUERY_GATE_INFO_RET) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWC_QUERY_GATE_INFO_RET) ProtoMessage() {}

func (x *GWC_QUERY_GATE_INFO_RET) ProtoReflect() protoreflect.Message {
	mi := &file_GWC_PBMessage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWC_QUERY_GATE_INFO_RET.ProtoReflect.Descriptor instead.
func (*GWC_QUERY_GATE_INFO_RET) Descriptor() ([]byte, []int) {
	return file_GWC_PBMessage_proto_rawDescGZIP(), []int{14}
}

func (x *GWC_QUERY_GATE_INFO_RET) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *GWC_QUERY_GATE_INFO_RET) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

var File_GWC_PBMessage_proto protoreflect.FileDescriptor

var file_GWC_PBMessage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x47, 0x57, 0x43, 0x5f, 0x50, 0x42, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x0a, 0x43, 0x47, 0x57, 0x5f, 0x56, 0x45, 0x52,
	0x49, 0x46, 0x59, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x73, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x73, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x69, 0x64, 0x22, 0x46, 0x0a,
	0x0a, 0x47, 0x57, 0x43, 0x5f, 0x56, 0x45, 0x52, 0x49, 0x46, 0x59, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x73, 0x72, 0x65, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x27, 0x0a, 0x09, 0x43, 0x47, 0x57, 0x5f, 0x48, 0x45, 0x41,
	0x52, 0x54, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x5e,
	0x0a, 0x16, 0x43, 0x47, 0x57, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x47, 0x41,
	0x4d, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x73, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x69, 0x73, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x50,
	0x0a, 0x1a, 0x47, 0x57, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x47, 0x41,
	0x4d, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x54, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x75, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75, 0x63, 0x12, 0x20,
	0x0a, 0x0b, 0x69, 0x73, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x73, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x22, 0x3e, 0x0a, 0x1a, 0x43, 0x47, 0x57, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x20,
	0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x44, 0x0a, 0x1e, 0x47, 0x57, 0x43, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f,
	0x47, 0x41, 0x4d, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52,
	0x45, 0x54, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x18, 0x43, 0x47, 0x57, 0x5f, 0x52, 0x45,
	0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x53, 0x45, 0x52, 0x56,
	0x45, 0x52, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x62, 0x6a, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x62, 0x6a,
	0x69, 0x64, 0x22, 0x2b, 0x0a, 0x09, 0x47, 0x57, 0x43, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x69, 0x6d, 0x65, 0x22,
	0x12, 0x0a, 0x10, 0x43, 0x47, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x48, 0x45,
	0x41, 0x52, 0x54, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x57, 0x43, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e,
	0x54, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x22, 0xcf, 0x03, 0x0a, 0x10, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x57, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x57,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6f, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6f, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61,
	0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x64,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x64, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x73, 0x70, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x22, 0x0a, 0x0c, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x48, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2d, 0x0a, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x4a, 0x4a, 0x10, 0x02, 0x22, 0x9a, 0x02, 0x0a, 0x10, 0x43, 0x47,
	0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x12, 0x20,
	0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x61, 0x78, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x4d, 0x61, 0x78, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x31, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x37, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45,
	0x53, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4a, 0x4a,
	0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x4d, 0x5f, 0x4c,
	0x4f, 0x47, 0x49, 0x4e, 0x10, 0x03, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x47, 0x57, 0x5f, 0x51, 0x55,
	0x45, 0x52, 0x59, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x22, 0x47, 0x0a,
	0x17, 0x47, 0x57, 0x43, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x54, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x62, 0x2f,
}

var (
	file_GWC_PBMessage_proto_rawDescOnce sync.Once
	file_GWC_PBMessage_proto_rawDescData = file_GWC_PBMessage_proto_rawDesc
)

func file_GWC_PBMessage_proto_rawDescGZIP() []byte {
	file_GWC_PBMessage_proto_rawDescOnce.Do(func() {
		file_GWC_PBMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_GWC_PBMessage_proto_rawDescData)
	})
	return file_GWC_PBMessage_proto_rawDescData
}

var file_GWC_PBMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_GWC_PBMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_GWC_PBMessage_proto_goTypes = []interface{}{
	(DeviceInfoClient_ChannelId)(0),        // 0: DeviceInfoClient.ChannelId
	(CGW_CLIENT_LOGIN_LoginType)(0),        // 1: CGW_CLIENT_LOGIN.LoginType
	(*CGW_VERIFY)(nil),                     // 2: CGW_VERIFY
	(*GWC_VERIFY)(nil),                     // 3: GWC_VERIFY
	(*CGW_HEART)(nil),                      // 4: CGW_HEART
	(*CGW_CONNECT_GAMESERVER)(nil),         // 5: CGW_CONNECT_GAMESERVER
	(*GWC_CONNECT_GAMESERVER_RET)(nil),     // 6: GWC_CONNECT_GAMESERVER_RET
	(*CGW_REQUEST_GAMESERVERINFO)(nil),     // 7: CGW_REQUEST_GAMESERVERINFO
	(*GWC_REQUEST_GAMESERVERINFO_RET)(nil), // 8: GWC_REQUEST_GAMESERVERINFO_RET
	(*CGW_RECONNECT_GAMESERVER)(nil),       // 9: CGW_RECONNECT_GAMESERVER
	(*GWC_HEART)(nil),                      // 10: GWC_HEART
	(*CGW_CLIENT_HEART)(nil),               // 11: CGW_CLIENT_HEART
	(*GWC_CLIENT_HEART)(nil),               // 12: GWC_CLIENT_HEART
	(*DeviceInfoClient)(nil),               // 13: DeviceInfoClient
	(*CGW_CLIENT_LOGIN)(nil),               // 14: CGW_CLIENT_LOGIN
	(*CGW_QUERY_GATE_INFO)(nil),            // 15: CGW_QUERY_GATE_INFO
	(*GWC_QUERY_GATE_INFO_RET)(nil),        // 16: GWC_QUERY_GATE_INFO_RET
}
var file_GWC_PBMessage_proto_depIdxs = []int32{
	13, // 0: CGW_CLIENT_LOGIN.deviceInfo:type_name -> DeviceInfoClient
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_GWC_PBMessage_proto_init() }
func file_GWC_PBMessage_proto_init() {
	if File_GWC_PBMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GWC_PBMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_VERIFY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWC_VERIFY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_HEART); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_CONNECT_GAMESERVER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWC_CONNECT_GAMESERVER_RET); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_REQUEST_GAMESERVERINFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWC_REQUEST_GAMESERVERINFO_RET); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_RECONNECT_GAMESERVER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWC_HEART); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_CLIENT_HEART); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWC_CLIENT_HEART); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfoClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_CLIENT_LOGIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CGW_QUERY_GATE_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GWC_PBMessage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWC_QUERY_GATE_INFO_RET); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GWC_PBMessage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GWC_PBMessage_proto_goTypes,
		DependencyIndexes: file_GWC_PBMessage_proto_depIdxs,
		EnumInfos:         file_GWC_PBMessage_proto_enumTypes,
		MessageInfos:      file_GWC_PBMessage_proto_msgTypes,
	}.Build()
	File_GWC_PBMessage_proto = out.File
	file_GWC_PBMessage_proto_rawDesc = nil
	file_GWC_PBMessage_proto_goTypes = nil
	file_GWC_PBMessage_proto_depIdxs = nil
}
